module TDO.Localization.Packages
import Codeware.Localization.*

public class English extends ModLocalizationPackage {
  protected func DefineSubtitles() {}

  protected func DefineTexts() -> Void {
    
    this.Text("Item-TDO-C1Shrike-Name", "Zetatech \"Shrike\" Sandevistan");
    this.Text("Item-TDO-C2Tanto-Name", "Dynalar \"Tanto\" Sandevistan");

    
    this.Text("Item-TDO-C1Shrike-Flavor", "Zetatech precision-execution subroutine — paint your targets while time crawls, then watch them all drop at once.");
    this.Text("Item-TDO-C1Shrike-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nAim at a hostile within <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_7}m</> to mark it (up to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_5}</> marks).\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> (you are not slowed)\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">ADS</> to track the closest <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">mark</> with an <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">aimbot-like</> effect. Pull the trigger to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">execute</> the target.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_4}% headshot damage</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_4}% weakspot damage</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_6} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_3} sec.");

    
    this.Text("Item-TDO-C2Tanto-Flavor", "Dynalar blade discipline. Parry the strike, vanish into time, finish from behind.");
    this.Text("Item-TDO-C2Tanto-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nBuild <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Phantom Strike</> charges by performing a perfect parry/melee crit/finisher. Max <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_5}</> charges.\n\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Requires a blade weapon.</>\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> (you are not slowed)\nWhile blocking with a blade, press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">phase</> behind your target (within <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_4}m</>) - your next attack is a guaranteed <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">crit</>. Costs one charge.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}% Crit Chance</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}% Crit Damage</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_3} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_6} sec.");

    
    this.Text("Item-TDO-Apogee-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</> and <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">deactivate</>.\nActivates at <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">any charge level</> and lasts <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">indefinitely</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> indefinitely (you are not slowed).\nTime speeds back toward real-time as you <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">move or act</>.\nHolding one spot builds <Rich color=\"MainColors.Red\" style=\"Semi-Bold\">biological strain</> that drains your health the longer you stay - keep moving to bleed it off.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}% Headshot Damage</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}% Crit Chance</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}% Crit Damage</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_6} sec.");

    this.Text("Attunement-TDO-Apogee-Name", "Reflexes Attuned");
    this.Text("Attunement-TDO-Apogee-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> of strain grace before the health drain begins, with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</>");

    this.Text("Item-TDO-Falcon-Name", "Militech \"Falcon\" Sandevistan");
    this.Text("Item-TDO-Falcon-Flavor", "Militech targeting subroutine — the gun knows what it is, and Falcon knows what to do with it.");
    this.Text("Item-TDO-Falcon-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> (you are not slowed)\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Power - Trick Shot</>: bullets ricochet on every hit, wide angle. <Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Cannot reload while active. Your own ricochets can hit you within 2m — up to 10% Max HP per ricochet.</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Tech - Bolt Shot</>: Overcharges the Bolt perk, causing each usage to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">pierce</> all obstacles, and <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">detonates</> an <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">EMP</> blast at the impact point. Tech weapons charge at full speed in time dilation. <Rich color=\"MainColors.Red\" style=\"Semi-Bold\">10% Max HP cost per shot. Requires Bolt Shot perk.</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Smart - Saturation Lock</>: ADS to lock every visible enemy, fire to volley them all. <Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Cyberware disabled after Sandy ends, proportional to Smart shots fired.</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_6} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_7} sec.");

    
    this.Text("SE-TDO-Cooldown-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_0} sec.");

    
    this.Text("SE-TDO-QuantumSpareCharge-Name", "Quantum Charges");
    this.Text("SE-TDO-QuantumSpareCharge-Desc", "Remaining Sandevistan activations. Each press consumes one stack. Full cooldown replenishes both.");

    
    this.Text("SE-TDO-KurosawaMark-Name", "Kurosawa Mark");
    this.Text("SE-TDO-KurosawaMark-Desc", "Stored damage from Kurosawa Sandevistan. Releases as a chain reaction on Sandevistan exit. More stacks = bigger blast.");

    
    this.Text("SE-TDO-TantoCharge-Name", "Phantom Strike Charge");
    this.Text("SE-TDO-TantoCharge-Desc", "Tanto teleport charges available. Hold block during Sandevistan and press activation to teleport behind a hostile.");
    this.Text("SE-TDO-TantoTeleportCrit-Name", "Phantom Strike");
    this.Text("SE-TDO-TantoTeleportCrit-Desc", "Your next melee strike is a guaranteed critical hit.");
    this.Text("SE-TDO-TantoCritUsed-Name", "Phantom Strike Locked");
    this.Text("SE-TDO-TantoCritUsed-Desc", "This target has already granted a Phantom Strike charge from a critical hit.");
    this.Text("Attunement-TDO-Tanto-Name", "Reflexes Attuned");
    this.Text("Attunement-TDO-Tanto-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Sandevistan duration / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}m</> Phantom Strike range with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</> / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}m.</>");
    this.Text("Attunement-TDO-WarpDancer-Name", "Cool Attuned");
    this.Text("Attunement-TDO-WarpDancer-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Sandevistan duration / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">-{float_2}%</> Sandevistan recharge time with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</> / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">-{float_3}%.</>");
    
    this.Text("SE-TDO-ZetatechRangedBuff-Name", "Zetatech Mark & Execute");
    this.Text("SE-TDO-ZetatechRangedBuff-Desc", "Mark & Execute active. ADS to mark hostiles in LOS within 50m. ADS during Sandevistan to track the closest mark, pull the trigger to execute.");

    
    this.Text("SE-TDO-FalconRangedBuff-Name", "Militech Targeting Subroutine");
    this.Text("SE-TDO-FalconRangedBuff-Desc", "Power: ricochet count and damage. Tech: faster charge. Smart: faster lock-on. Bonuses scale with TechnicalAbility via Falcon attunement.");

    
    this.Text("SE-TDO-FalconLockMarker-Name", "Saturation Lock");
    this.Text("SE-TDO-FalconLockMarker-Desc", "Falcon Sandevistan has marked this target for saturation lock. Trigger pull on ADS release fires a guided bullet to the marked weakspot.");
    this.Text("SE-TDO-QuantumMalware-Name", "Quantum Malware");
    this.Text("SE-TDO-QuantumMalware-Desc", "Quantum Sandevistan implanted malware into this target, locking it in dilated time.");

    
    this.Text("Attunement-TDO-Shrike-Name", "Reflexes Attuned");
    this.Text("Attunement-TDO-Shrike-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Sandevistan duration with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</>");

    
    this.Text("Attunement-TDO-Falcon-Name", "Technical Ability Attuned");
    this.Text("Attunement-TDO-Falcon-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Sandevistan duration / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}%</> weapon-type bonus with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</> / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}%</> (cap 10% at Technical Ability 20).");

    
    this.Text("Item-TDO-Sogimsu-Name", "Arasaka \"Watchdog\" Operating System");
    this.Text("Item-TDO-Sogimsu-Flavor", "Arasaka corporate-grade Watchdog Protocol. A reactive AI counter-detection subroutine that runs in the background, auto-quickhacking enemies that spot you. No time dilation — pure cyber warfare.");
    this.Text("Item-TDO-Sogimsu-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>. Press again to cancel.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Watchdog Protocol</> automatically <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">intervenes</> to upload <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Memory Wipe</> + <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Reboot Optics</> to any hostile about to detect you.\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Ends early if you are pulled into combat.</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}% Detection Speed Decrease</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}% Stealth Hit Damage</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_4} interventions per Watchdog Protocol</>\n\nWhen it ends:\nApplies an empowered version of <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Optical Camo</> for <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_5} sec</> for repositioning.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_0} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_1} sec.");
    this.Text("Attunement-TDO-Sogimsu-Name", "Cool Attuned");
    this.Text("Attunement-TDO-Sogimsu-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> end-of-Watchdog Optical Camo with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</>");
    this.Text("SE-TDO-SogimsuWatchdog-Name", "Watchdog Protocol Active");
    this.Text("SE-TDO-SogimsuWatchdog-Desc", "Reactive AI counter-detection running. Auto-quickhacks hostiles that spot you (yellow bar or higher). On end, Optical Camo activates.");
    this.Text("SE-TDO-SogimsuCamo-Name", "Sogimsu Optical Camo");
    this.Text("SE-TDO-SogimsuCamo-Desc", "Optical camouflage active. You are invisible to enemies.");

    
    this.Text("Item-TDO-Juggernaut-Name", "Anvil Defense \"Juggernaut\" Operating System");
    this.Text("Item-TDO-Juggernaut-Flavor", "Anvil Defense military chassis OS. Lock down, take everything, give it all back. Body-attuned defensive system — no time dilation.");
    this.Text("Item-TDO-Juggernaut-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to activate.\n\nWhen active:\nEngages <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Armor Lock</> to absorb up to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}</> incoming damage.\nYou have full <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">status effect</> immunity. Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to end <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Armor Lock</> early, or let it auto release by hitting the absorb cap.\n\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">You cannot take offensive or defensive action during Armor Lock.</>\n\nOn release:\nThe absorbed damage <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">detonates</> as a <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_1}m shockwave</>. Enemies in a 360 degree range take full damage, and are <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">knocked down</> by the kinetic energy.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_0} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_3} sec.");
    this.Text("Attunement-TDO-Juggernaut-Name", "Body Attuned");
    this.Text("Attunement-TDO-Juggernaut-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0}%</> damage and fall damage reduction with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}%</>");
    this.Text("SE-TDO-JuggernautActive-Name", "Armor Lock");
    this.Text("SE-TDO-JuggernautActive-Desc", "Locked in place. All incoming damage is absorbed and stored for kinetic release.");

    
    this.Text("Item-TDO-Pyrolith-Name", "Wraith Munitions \"Pyrolith\" Operating System");
    this.Text("Item-TDO-Pyrolith-Flavor", "Wraith Munitions demolition OS. The nanites don't just rig your bullets — they teach your explosions to remember themselves. One blast becomes two. One kill becomes a chain.");
    this.Text("Item-TDO-Pyrolith-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\nRanged hits detonate a <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_1}m</> thermal explosion for <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}</> damage.\nThrown grenades release <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_3}</> cluster bomb(s) of the same type at <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_4}%</> of grenade damage.\n\nPassive:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_5}%</> grenade throw range.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">-80%</> grenade cooldown.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_0} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_6} sec.");
    this.Text("Attunement-TDO-Pyrolith-Name", "Technical Ability Attuned");
    this.Text("Attunement-TDO-Pyrolith-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0}%</> explosion damage resistance with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}%.</>");
    this.Text("SE-TDO-PyrolithActive-Name", "Pyrolith Online");
    this.Text("SE-TDO-PyrolithActive-Desc", "Pyrolith engaged. Bullets detonate on impact.");

    
    this.Text("SE-TDO-WarpDancerStagger-Name", "Temporal Recoil");
    this.Text("SE-TDO-WarpDancerStagger-Desc", "Snapped back through time. Brief disorientation as the world catches up.");

    
    this.Text("Item-TDO-WarpDancer-Name", "QianT \"Warp Dancer\" Sandevistan");
    this.Text("Item-TDO-WarpDancer-Flavor", "QianT temporal slip — capture the moment, return to it. Deepest dive in the lineup, paid for in recovery time.");
    this.Text("Item-TDO-WarpDancer-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> (you are not slowed)\nYour position is <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">recorded</> when using this cyberware. Certain Actions may be <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">frozen</> due to the extreme temporal strength.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_5}% move speed</>\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Infinite stamina during activation</>\n\nUpon Expiring:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Rewinds</> you back along your <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">recorded path</> over <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_8} sec</>. All attacks against other entities are <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">unfrozen</> and applied all at once.\nYou are <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">staggered</> for <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_6} sec</> due to the temporal whiplash.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_4} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_7} sec.");

    
    this.Text("Item-TDO-Fusillade-Name", "Raven \"Fusillade\" Sandevistan");
    this.Text("Item-TDO-Fusillade-Flavor", "Raven has no factory. Raven has no corp headquarters. What Raven has is a circuit that tells your trigger finger \"there is no maximum.\"");
    this.Text("Item-TDO-Fusillade-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_0}%</> (you are not slowed)\nYour weapons fire <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_1}x faster</> than their normal rate.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">No critical hits or weakspot damage.</>\nEach hit ramps damage: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}%</> first hit, <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}%</> per successive hit, up to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">100%</>.\n\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Missing resets your damage ramp to zero.</>\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">Recoil is increased by {float_4}%.</>\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_5} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_6} sec.");

    
    this.Text("Item-TDO-Kurosawa-Name", "Fuyutsuki \"Kurosawa\" Sandevistan");
    this.Text("Item-TDO-Kurosawa-Flavor", "The old blade-makers say a strike lands before the body falls. Fuyutsuki built the cyberware to prove it.");
    this.Text("Item-TDO-Kurosawa-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">No world time dilation.</>\n\nWhen active (melee only):\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Melee</> hits slow enemies by <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_0}%</> for the rest of this Sandevistan.\n\nKilling a slowed enemy <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">dismembers</> it after 1 sec, heals <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}%</> max health, and <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">refunds</> duration.\n\nA <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">finisher</> does this at <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">any health</> and <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">doubles</> the heal + refund.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}%</> Damage Reduction\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_3} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_4} sec.");

    
    this.Text("Item-TDO-Quantum-Name", "MoorE \"Quantum\" Sandevistan");
    this.Text("Item-TDO-Quantum-Flavor", "MoorE's experimental-line Sandevistan. The dealer won't tell you where the destination comes from. The dealer will, however, tell you to hold still until the teleport resolves.");
    this.Text("Item-TDO-Quantum-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_6}%</> (you are slowed)\nWhile slowed, aim a <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">teleport</> marker up to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_0}m</> away, then press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">warp</> to it.\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">You cannot act until you commit or cancel.</>\n\nUpon teleporting:\nApply <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Quantum Malware</> to the <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_1}</> nearest enemies within <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}m</>. They are individually slowed by <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_7}%</> for <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_3}</> sec.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_4} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_5} sec.");

    
    this.Text("Item-TDO-QuantumAdvanced-Name", "MoorE \"Quantum\" Advanced Sandevistan");
    this.Text("Item-TDO-QuantumAdvanced-Flavor", "Two-charge prototype. The whitecoat who'd know how it works isn't talking.");
    this.Text("Item-TDO-QuantumAdvanced-Active-Desc", "Press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">activate</>.\n\nWhen active:\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Slows time by {float_6}%</> (you are slowed)\nWhile slowed, aim a <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">teleport</> marker up to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_0}m</> away, then press <Input context=\"Abilities\" actionName=\"IconicCyberware\" color=\"MainColors.Blue\" hold=\"Hide\"></> to <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">warp</> to it.\n<Rich color=\"MainColors.Red\" style=\"Semi-Bold\">You cannot act until you commit or cancel.</>\n\nUpon teleporting:\nApply <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Quantum Malware</> to the <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_1}</> nearest enemies within <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_2}m</>. They are individually slowed by <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_7}%</> for <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">{float_3}</> sec.\n\nPassive:\nBanks <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">two teleport charges</>, usable back to back.\n\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Duration:</> {float_4} sec.\n<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">Cooldown:</> {float_5} sec.");

    
    this.Text("Attunement-TDO-Fusillade-Name", "Reflexes Attuned");
    this.Text("Attunement-TDO-Fusillade-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0}%</> ammo-refill chance per Attribute Point on ranged hits. Builds with your damage ramp, peaking at full ramp.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1}%.</>");

    this.Text("Attunement-TDO-Kurosawa-Body-Name", "Body Attuned");
    this.Text("Attunement-TDO-Kurosawa-Body-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Sandevistan duration refund on kill with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</>");

    this.Text("Attunement-TDO-Quantum-Name", "Cool Attuned");
    this.Text("Attunement-TDO-Quantum-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Quantum Malware freeze duration / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}m</> teleport range with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</> / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}m.</>");

    this.Text("Attunement-TDO-QuantumAdvanced-Name", "Cool Attuned");
    this.Text("Attunement-TDO-QuantumAdvanced-Desc", "<Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_0} sec.</> Quantum Malware freeze duration / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_2}m</> teleport range with this cyberware per Attribute Point.\nCurrent total: <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_1} sec.</> / <Rich color=\"TooltipText.cyberwareDescriptionHighlightColor\" style=\"Semi-Bold\">+{float_3}m.</>");

  }
}
